-- Users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

-- Swimming pools table
CREATE TABLE IF NOT EXISTS pools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

-- Amenities at pools (saunas, pools, facilities)
CREATE TABLE IF NOT EXISTS amenities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pool_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(100) NOT NULL, -- 'POOL', 'SAUNA', 'GYM', etc.
    FOREIGN KEY (pool_id) REFERENCES pools(id)
);

-- User reviews with penguin ratings
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    pool_id BIGINT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (pool_id) REFERENCES pools(id)
);

-- User check-ins to mark pools as visited
CREATE TABLE IF NOT EXISTS checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    pool_id BIGINT NOT NULL,
    visited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (pool_id) REFERENCES pools(id)
);